from typing import Any
from fastapi import FastAPI, APIRouter
from .Controllers.GetVideogameRecord import create_get_videogame_record_by_id_endpoint
from .Controllers.CreateVideogameRecord import create_videogame_record_endpoint
from .Controllers.DeleteVideogameRecord import delete_videogame_record_by_id_endpoint
from .Controllers.GetUserVideogameRecords import get_user_videogame_records_endpoint
from .Controllers.UpdateVideogameRecord import update_videogame_record_endpoint
from src.RecordLifecycle.application.UseCases.VideogameRecord.GetVideogameRecord.GetVideogameRecordHandler import GetVideogameRecordHandler
from src.RecordLifecycle.application.UseCases.VideogameRecord.CreateVideogameRecord.CreateVideogameRecordHandler import CreateVideogameRecordHandler
from src.RecordLifecycle.application.UseCases.VideogameRecord.DeleteVideogameRecord.DeleteVideogameRecordHandler import DeleteVideogameRecordHandler
from src.RecordLifecycle.application.UseCases.VideogameRecord.GetUserVideogameRecords.GetUserVideogameRecordsHandler import GetUserVideogameRecordsHandler
from src.RecordLifecycle.application.UseCases.VideogameRecord.UpdateVideogameRecord.UpdateVideogameRecordHandler import UpdateVideogameRecordHandler
from .Persistance.VideogameRecordRepositoryImpl import VideogameRecordRepositoryImpl
from dotenv import load_dotenv
import os
from pymongo import MongoClient
from pymongo.database import Database

client: MongoClient[dict[str, Any]]
database: Database[dict[str, Any]]

load_dotenv()

mongo_url = os.getenv("MONGODB_URL")
client = MongoClient(mongo_url)
database = client["base_de_datos"]

repo = VideogameRecordRepositoryImpl(database)
    
get_videogame_record_handler = GetVideogameRecordHandler(repo)
get_videogame_record_router = create_get_videogame_record_by_id_endpoint(get_videogame_record_handler)

create_videogame_record_handler = CreateVideogameRecordHandler(repo)
create_videogame_record_router = create_videogame_record_endpoint(create_videogame_record_handler)

delete_videogame_record_handler = DeleteVideogameRecordHandler(repo)
delete_videogame_record_router = delete_videogame_record_by_id_endpoint(delete_videogame_record_handler)

get_user_videogame_records_handler = GetUserVideogameRecordsHandler(repo)
get_user_videogame_records_router = get_user_videogame_records_endpoint(get_user_videogame_records_handler)

update_videogame_record_handler = UpdateVideogameRecordHandler(repo)
update_videogame_record_router = update_videogame_record_endpoint(update_videogame_record_handler)

videogame_record_router = APIRouter(prefix="/VideogamesRecords", tags=["VideogamesRecordsRoutes"])
app = FastAPI()
videogame_record_router.include_router(get_videogame_record_router)
videogame_record_router.include_router(create_videogame_record_router)
videogame_record_router.include_router(delete_videogame_record_router)
videogame_record_router.include_router(get_user_videogame_records_router)
videogame_record_router.include_router(update_videogame_record_router)
app.include_router(videogame_record_router)